name: Build Android APK
on:
workflow_dispatch:
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4
  - name: Setup Java 17
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: '17'

  - name: Install system deps
    run: |
      sudo apt-get update
      sudo apt-get install -y python3-venv python3-dev build-essential git zip unzip libffi-dev libssl-dev

  - name: Create venv and install tools
    run: |
      python3 -m venv .venv
      source .venv/bin/activate
      python -m pip install --upgrade pip
      pip install cython buildozer
      pip install kivy requests certifi

  - name: Build APK (debug)
    run: |
      source .venv/bin/activate
      buildozer android debug

  - name: Upload APK artifact
    uses: actions/upload-artifact@v4
    with:
      name: eurusd-apk
      path: bin/*.apk
